# These are supported funding model platforms, all fields are currently disabled
# Uncomment and configure any of these if/when sponsorship becomes relevant

# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# issuehunt: # Replace with a single IssueHunt username e.g., user1
# ko_fi: # Replace with a single Ko-fi username e.g., user1
# liberapay: # Replace with a single Liberapay username e.g., user1
# open_collective: # Replace with a single Open Collective username e.g., user1
# patreon: # Replace with a single Patreon username e.g., user1
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# polar: # Replace with a single Polar username e.g., user1
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username e.g., user1
# thanks_dev: # Replace with a single thanks.dev username e.g., u/gh/user1
# otechie: # Replace with a single Otechie username e.g., user1
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
