name: ✨ Feature request
description: 💡 Suggest a new feature or improvement
title: "[Feature]: 🚀"
labels: ["feature request", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for suggesting a feature! Please fill out the following fields to help us understand your request. 📝

  - type: checkboxes
    id: terms
    attributes:
      label: 📜 Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/krisztianmukli/.github/blob/main/CONTRIBUTING.md).
      options:
        - label: ✅ I agree to follow this project's Contributing Guidelines.
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 🆕 Feature Type
      description: Is this a completely new feature or an improvement to an existing one?
      options:
        - ✨ New feature
        - 🔁 Enhancement of existing feature
      multiple: false
    validations:
      required: true
      
  - type: dropdown
    id: feature-category
    attributes:
      label: 🧭 Feature Category
      description: What area of the project would this feature affect?
      options:
        - 🎨 UI / UX
        - 🔧 Core functionality
        - 🔌 API / Integration
        - 🗃️ Data handling / Storage
        - 🌍 Internationalization / Localization
        - 🚀 Performance improvement
        - 🔐 Security enhancement
        - 📖 Documentation
        - ⚙️ Configuration / Setup
        - 🧪 Testing / QA
        - 🔄 Developer tooling
        - ❓ Other (please specify below)
      multiple: false
    validations:
      required: true                

  - type: textarea
    id: description
    attributes:
      label: ✍️ Feature Description
      description: Describe the feature or improvement you'd like to see.
      placeholder: What should be added or improved?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🛠 Problem
      description: Is this feature related to a specific problem or limitation?
      placeholder: What problem does this feature solve?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 🧠 Suggested Solution
      description: How do you envision this feature working?
      placeholder: Describe the desired implementation or behavior.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you thought of other ways to achieve the same goal?
      placeholder: List any alternative solutions or workarounds.
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other information, screenshots, or use cases that may help.
      placeholder: Optional but helpful context or examples.
    validations:
      required: false
